"""init migra

Revision ID: f49938a13cc5
Revises: 
Create Date: 2024-09-10 10:46:56.887584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49938a13cc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('supplier', sa.String(length=50), nullable=True),
    sa.Column('is_cat_a', sa.Boolean(), nullable=False),
    sa.Column('artikelnummer', sa.String(length=50), nullable=True),
    sa.Column('beschreibung', sa.String(length=255), nullable=True),
    sa.Column('farbe', sa.String(length=50), nullable=True),
    sa.Column('ean', sa.String(length=50), nullable=True),
    sa.Column('vpe', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
